const data = {
  users: [
    {
      loan_id: "1214354",
      purpose: "lorem ipssum dolor set",
      status: "progress",
      first_name: "Kishor",
      last_name: "TH",
      email: "kishor@gmail.com",
      region: "India",
    },
    {
      loan_id: "43343434",
      purpose: "lorem ipssum dolor set",
      status: "progress",
      first_name: "Aswin",
      last_name: "S",
      email: "aswin@gmail.com",
      region: "India",
    },
    {
      loan_id: "535453",
      purpose: "lorem ipssum dolor set",
      status: "progress",
      first_name: "Ajmal",
      last_name: "Rishad",
      email: "ajmal@gmail.com",
      region: "Dubai",
    },
    {
      loan_id: "84373",
      purpose: "lorem ipssum dolor set",
      status: "progress",
      first_name: "ALan",
      last_name: "Anto",
      email: "alan@gmail.com",
      region: "Australia",
    },
    {
      loan_id: "535353",
      purpose: "lorem ipssum dolor set",
      status: "progress",
      first_name: "Ashish",
      last_name: "G",
      email: "ashish@gmail.com",
      region: "USA",
    },
    {
      loan_id: "434343434",
      purpose: "lorem ipssum dolor set",
      status: "progress",
      first_name: "Assim",
      last_name: "S",
      email: "assim@gmail.com",
      region: "India",
    },
    {
      loan_id: "5353535",
      purpose: "lorem ipssum dolor set",
      status: "progress",
      first_name: "akshay",
      last_name: "Raj",
      email: "akshay@gmail.com",
      region: "Bangladesh",
    },
    {
      loan_id: "7857585",
      purpose: "lorem ipssum dolor set",
      status: "progress",
      first_name: "Abhishek",
      last_name: "S",
      email: "asp@gmail.com",
      region: "India",
    },
  ],
};
module.exports = data;
